server:
  port: 8080
  servlet:
    context-path: /

spring:
  #ehcache配置文件
  cache:
    ehcache:
      config: 'classpath:ehcache.xml'

  #druid数据源
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      # 连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 100
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.xxd.servie.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: xxd11111
        login-password: xxd11111
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

#mybatis plus 设置
mybatis-plus:
  # 实体路径
  type-aliases-package: com.vkl.entity
  #xml扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #删除逻辑
      logic-delete-value: 1
      logic-not-delete-value: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断" 3:"默认"
      insert-strategy: default
      update-strategy: default
      where-strategy: default
      #驼峰下划线转换
      table-underline: true
      #数据库大写下划线转换
      capital-mode: true
  #打印sql，生产环境误开
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

